name: Build SK UnrealFarm Installer

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # ------------------------
    # Python Setup
    # ------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install pyinstaller

    # ------------------------
    # Build Manager
    # ------------------------
    - name: Build Manager
      run: |
        pyinstaller --onefile manager/manager.py
        if not exist "package\manager" mkdir package\manager
        copy dist\manager.exe package\manager\

    # ------------------------
    # Build Worker
    # ------------------------
    - name: Build Worker
      run: |
        pyinstaller --onefile worker/worker.py
        if not exist "package\worker" mkdir package\worker
        copy dist\worker.exe package\worker\

    # ------------------------
    # Copy Config
    # ------------------------
    - name: Copy Config
      run: |
        if not exist "package" mkdir package
        copy config.json package\

    # ------------------------
    # Download NSSM
    # ------------------------
    - name: Download NSSM
      run: |
        powershell -Command "Invoke-WebRequest -Uri 'https://nssm.cc/download/nssm-2.24-101-g897c7f7.zip' -OutFile 'nssm.zip'"
        powershell -Command "Expand-Archive -Path 'nssm.zip' -DestinationPath '.' -Force"
        copy "nssm-2.24-101-g897c7f7\win64\nssm.exe" package\

    # ------------------------
    # Install Inno Setup
    # ------------------------
    - name: Install Inno Setup
      run: choco install innosetup -y

    # ------------------------
    # Compile Installer
    # ------------------------
    - name: Compile Installer
      shell: cmd
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\SK_UnrealFarm_AllInOne.iss'

    # ------------------------
    # Upload Installer
    # ------------------------
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: SK-UnrealFarm-Installer
        path: Output\*.exe
